<?php

declare(strict_types=1);

namespace Semitexa\ProjectGraph\Tests\Integration;

use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Semitexa\ProjectGraph\Application\Service\Coverage\CoverageGapKind;
use Semitexa\ProjectGraph\Application\Service\Graph\EdgeType;
use Semitexa\ProjectGraph\Tests\Support\GraphFixture;

/**
 * What the graph deliberately does not look at must be visible as such.
 * #[GraphIgnore] was declared and documented but read by nothing, and the
 * scanner's exclusions were not counted anywhere.
 */
final class IgnoredAndExcludedTest extends TestCase
{
    #[Test]
    public function a_graph_ignored_class_leaves_the_graph_and_a_gap_with_its_reason(): void
    {
        $fixture = GraphFixture::built();
        $fixture->write('Cycle/Pong.php', str_replace(
            'final class Pong',
            "#[\\Semitexa\\ProjectGraph\\Attribute\\GraphIgnore(reason: 'generated by a tool')]\nfinal class Pong",
            $fixture->read('Cycle/Pong.php'),
        ));
        $fixture->refresh();

        $pong = GraphFixture::classId('Cycle\\Pong');
        $ping = GraphFixture::classId('Cycle\\Ping');

        self::assertFalse($fixture->hasEdge(EdgeType::Instantiates, $pong, $ping), 'its own edges are gone');
        self::assertTrue($fixture->hasEdge(EdgeType::Instantiates, $ping, $pong), 'references to it are real and stay');
        self::assertTrue($fixture->storage->nodes->findById($pong)?->getIsPlaceholder() ?? false);

        $gaps = $fixture->storage->gaps->findAll(CoverageGapKind::Ignored);
        self::assertCount(1, $gaps);
        self::assertSame(GraphFixture::NS . 'Cycle\\Pong', $gaps[0]->getSubject());
        self::assertSame('generated by a tool', $gaps[0]->getDetail());
    }

    #[Test]
    public function the_scan_counts_what_each_rule_kept_out(): void
    {
        $fixture = GraphFixture::create();
        $fixture->write('.graphignore', "Generated/\n*.skip.php\n");
        $fixture->write('Generated/Stub.php', "<?php\n");
        $fixture->write('Generated/Deeper/Stub2.php', "<?php\n");
        $fixture->write('Orders/Legacy.skip.php', "<?php\n");
        $fixture->write('vendor/acme/Lib.php', "<?php\n");
        $fixture->write('Docs/Checkout.example.php', "<?php\nnamespace App;\nfinal class Checkout\n{\n}\n");
        $fixture->build();

        $exclusions = json_decode((string) $fixture->storage->getMeta('coverage_exclusions'), true);

        self::assertSame(['*.example.php' => 1, '*.skip.php' => 1, 'Generated/' => 1, 'dir:vendor' => 1], $exclusions);
        self::assertFalse($fixture->storage->nodeExists('class:App\\Checkout'), 'documentation snippets are not project code');
        self::assertFalse($fixture->storage->nodeExists('class:Stub'));
    }
}
